// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKZyy6YM149jditUmL9TbAq_hvdZMl1M',
    appId: '1:142651066073:web:adec2ec1d96724eb1320c8',
    messagingSenderId: '142651066073',
    projectId: 'nss-community-connect',
    authDomain: 'nss-community-connect.firebaseapp.com',
    storageBucket: 'nss-community-connect.appspot.com',
    measurementId: 'G-TC6NQT7VZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KaqvR0_n04daw8JEJe-qQO55kuT2cJY',
    appId: '1:142651066073:android:5858e465ee97df0d1320c8',
    messagingSenderId: '142651066073',
    projectId: 'nss-community-connect',
    storageBucket: 'nss-community-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9YcjwLilSBFNcgn5YL9DskoVZH3PQVz4',
    appId: '1:142651066073:ios:90518970516e9d4b1320c8',
    messagingSenderId: '142651066073',
    projectId: 'nss-community-connect',
    storageBucket: 'nss-community-connect.appspot.com',
    iosBundleId: 'com.example.taskNss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9YcjwLilSBFNcgn5YL9DskoVZH3PQVz4',
    appId: '1:142651066073:ios:90518970516e9d4b1320c8',
    messagingSenderId: '142651066073',
    projectId: 'nss-community-connect',
    storageBucket: 'nss-community-connect.appspot.com',
    iosBundleId: 'com.example.taskNss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcKZyy6YM149jditUmL9TbAq_hvdZMl1M',
    appId: '1:142651066073:web:cf63496f56e4002e1320c8',
    messagingSenderId: '142651066073',
    projectId: 'nss-community-connect',
    authDomain: 'nss-community-connect.firebaseapp.com',
    storageBucket: 'nss-community-connect.appspot.com',
    measurementId: 'G-9NHKV2J0TQ',
  );

}